# Generated by Django 5.0.6 on 2024-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
