# Generated by Django 5.0.6 on 2024-05-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_producer_is_hiring_producer_stage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='stage_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='store',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
