# Generated by Django 5.0.7 on 2024-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_rename_user_producerstore_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='producer_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
