# Generated by Django 5.0.6 on 2024-05-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='sex',
        ),
    ]
