# Generated by Django 5.0.7 on 2024-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talent', '0002_remove_talent_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='talent_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
