# Generated by Django 5.0.6 on 2024-06-04 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FetosJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('job_date_time', models.DateTimeField()),
                ('job_description', models.CharField(max_length=155)),
                ('level_of_nudity', models.CharField(choices=[('clothed', 'Clothed'), ('topless', 'Topless'), ('nude', 'Nude'), ('explicit', 'Explicit')], max_length=15)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
