# Generated by Django 5.0.6 on 2024-06-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='fetosjob',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fetosjob',
            name='number_of_talent_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fetosjob',
            name='sex_needed',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('trans_male', 'Trans Male'), ('trans_female', 'Trans Female'), ('non_binary', 'Non-Binary')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='fetosjob',
            name='level_of_nudity',
            field=models.CharField(choices=[('clothed', 'Clothed'), ('topless', 'Topless'), ('nude', 'Nude'), ('explicit', 'Explicit')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='fetosjob',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fetos_jobs.categories'),
        ),
    ]
