# Generated by Django 5.0.6 on 2024-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0002_categories_fetosjob_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
