# Generated by Django 5.0.6 on 2024-06-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0004_alter_categories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetosjob',
            name='categories',
            field=models.CharField(max_length=255),
        ),
    ]
