# Generated by Django 5.0.6 on 2024-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0006_rename_categories_categoriesref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetosjob',
            name='categories',
            field=models.JSONField(),
        ),
    ]
