# Generated by Django 5.0.6 on 2024-07-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0007_alter_fetosjob_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesref',
            name='description',
        ),
    ]
