# Generated by Django 5.0.6 on 2024-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0009_fetosjob_model_options_fetosjob_pay_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetosjob',
            name='job_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fetosjob',
            name='travel_stipend_amount',
            field=models.IntegerField(default=None),
        ),
    ]
