# Generated by Django 5.0.7 on 2024-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetos_jobs', '0010_alter_fetosjob_job_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetosjob',
            name='level_of_nudity',
            field=models.CharField(choices=[('clothed', 'Clothed'), ('topless', 'Topless'), ('nude', 'Nude'), ('explicit', 'Explicit')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='fetosjob',
            name='pay_structure',
            field=models.CharField(choices=[('per_hour', 'Per Hour'), ('per_finished_minute', 'Per Finished Minute'), ('per_video', 'Per Video'), ('day_rate', 'Day Rate')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='fetosjob',
            name='sex_needed',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('trans_male', 'Trans Male'), ('trans_female', 'Trans Female'), ('non_binary', 'Non-Binary')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='fetosjob',
            name='travel_options',
            field=models.CharField(choices=[('flight', 'Flight'), ('flight_and_lodging', 'Flight & Lodging'), ('travel_stipend', 'Travel Stipend')], default=None, max_length=50),
        ),
    ]
