# Generated by Django 5.0.6 on 2024-05-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('producer', 'Producer'), ('talent', 'Talent')], default=None, max_length=10),
        ),
    ]
