# Generated by Django 5.0.6 on 2024-05-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0004_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address_line_two',
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=55),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('trans_male', 'Trans Male'), ('trans_female', 'Trans Female'), ('non_binary', 'Non-Binary')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_bio',
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
