# Generated by Django 5.0.6 on 2024-05-26 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0005_remove_useraddress_address_line_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
