# Generated by Django 5.0.6 on 2024-05-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0006_alter_appuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('trans_male', 'Trans Male'), ('trans_female', 'Trans Female'), ('non_binary', 'Non-Binary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('producer', 'Producer'), ('talent', 'Talent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccounts',
            name='account_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaaccounts',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
