# Generated by Django 4.2.13 on 2024-05-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0007_alter_appuser_date_of_birth_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='sex',
        ),
    ]
