# Generated by Django 5.0.6 on 2024-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0008_remove_appuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('trans_male', 'Trans Male'), ('trans_female', 'Trans Female'), ('non_binary', 'Non-Binary')], max_length=20, null=True),
        ),
    ]
