# Generated by Django 5.0.6 on 2024-07-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0010_appuser_is_hiring_appuser_is_open_to_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_hiring',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_open_to_work',
        ),
    ]
