# Generated by Django 5.0.6 on 2024-07-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0011_remove_appuser_is_hiring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
    ]
