# Generated by Django 5.0.6 on 2024-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0013_rename_is_verified_appuser_is_verified_as_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_producer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_talent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_verified_as_producer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_verified_as_talent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
