# Generated by Django 5.0.7 on 2024-07-29 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0015_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_bio',
        ),
    ]
